version: v1.0
name: terraform-provider-ovh-website-test
jobs:
- job: checks
  steps:
  - name: Get the sources of the project
    checkout: '{{.cds.workspace}}'
  - name: website test
    script: |
      #!/usr/bin/env bash
      set -eEuo pipefail
      GOPATH=. make website-test

  requirements:
  - binary: docker
