version: v1.0
name: terraform-provider-ovh-check
jobs:
- job: checks
  steps:
  - name: Get the sources of the project
    checkout: '{{.cds.workspace}}'
  - name: checks
    script: |
      #!/usr/bin/env bash
      set -eEuo pipefail
      export GOFLAGS=-mod=vendor
      export GO111MODULE=on

      make test
      make vet
  requirements:
  - model: shared.infra/Go-official-1.19-bullseye
