// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package ovh

import (
	"context"
	ovhtypes "github.com/ovh/terraform-provider-ovh/v2/ovh/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CloudProjectStorageObjectDataSourceSchema(ctx context.Context) schema.Schema {
	attrs := map[string]schema.Attribute{
		"etag": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "ETag",
			MarkdownDescription: "ETag",
		},
		"is_delete_marker": schema.BoolAttribute{
			CustomType:          ovhtypes.TfBoolType{},
			Computed:            true,
			Description:         "Whether this object is a delete marker",
			MarkdownDescription: "Whether this object is a delete marker",
		},
		"is_latest": schema.BoolAttribute{
			CustomType:          ovhtypes.TfBoolType{},
			Computed:            true,
			Description:         "Whether this is the latest version of the object",
			MarkdownDescription: "Whether this is the latest version of the object",
		},
		"key": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Key",
			MarkdownDescription: "Key",
		},
		"last_modified": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Last modification date",
			MarkdownDescription: "Last modification date",
		},
		"name": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Name",
			MarkdownDescription: "Name",
		},
		"region_name": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Region name",
			MarkdownDescription: "Region name",
		},
		"service_name": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Service name",
			MarkdownDescription: "Service name",
		},
		"size": schema.Int64Attribute{
			CustomType:          ovhtypes.TfInt64Type{},
			Computed:            true,
			Description:         "Size (bytes)",
			MarkdownDescription: "Size (bytes)",
		},
		"storage_class": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Storage class",
			MarkdownDescription: "Storage class",
		},
		"version_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Version ID of the object",
			MarkdownDescription: "Version ID of the object",
		},
	}

	return schema.Schema{
		Attributes: attrs,
	}
}

type CloudProjectStorageObjectModel struct {
	Etag           ovhtypes.TfStringValue `tfsdk:"etag" json:"etag"`
	IsDeleteMarker ovhtypes.TfBoolValue   `tfsdk:"is_delete_marker" json:"isDeleteMarker"`
	IsLatest       ovhtypes.TfBoolValue   `tfsdk:"is_latest" json:"isLatest"`
	Key            ovhtypes.TfStringValue `tfsdk:"key" json:"key"`
	LastModified   ovhtypes.TfStringValue `tfsdk:"last_modified" json:"lastModified"`
	Name           ovhtypes.TfStringValue `tfsdk:"name" json:"name"`
	RegionName     ovhtypes.TfStringValue `tfsdk:"region_name" json:"regionName"`
	ServiceName    ovhtypes.TfStringValue `tfsdk:"service_name" json:"serviceName"`
	Size           ovhtypes.TfInt64Value  `tfsdk:"size" json:"size"`
	StorageClass   ovhtypes.TfStringValue `tfsdk:"storage_class" json:"storageClass"`
	VersionId      ovhtypes.TfStringValue `tfsdk:"version_id" json:"versionId"`
}
