// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package ovh

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	ovhtypes "github.com/ovh/terraform-provider-ovh/ovh/types"
)

func DbaasLogsClusterRetentionDataSourceSchema(ctx context.Context) schema.Schema {
	attrs := map[string]schema.Attribute{
		"cluster_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Cluster ID",
			MarkdownDescription: "Cluster ID",
		},
		"duration": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Optional:            true,
			Description:         "Indexed duration expressed in ISO-8601 format",
			MarkdownDescription: "Indexed duration expressed in ISO-8601 format",
		},
		"is_supported": schema.BoolAttribute{
			CustomType:          ovhtypes.TfBoolType{},
			Computed:            true,
			Description:         "Indicates if a new stream can use it",
			MarkdownDescription: "Indicates if a new stream can use it",
		},
		"retention_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Optional:            true,
			Description:         "Retention ID",
			MarkdownDescription: "Retention ID",
		},
		"service_name": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Service name",
			MarkdownDescription: "Service name",
		},
	}

	return schema.Schema{
		Attributes: attrs,
	}
}

type DbaasLogsClusterRetentionModel struct {
	ClusterId   ovhtypes.TfStringValue `tfsdk:"cluster_id" json:"clusterId"`
	Duration    ovhtypes.TfStringValue `tfsdk:"duration" json:"duration"`
	IsSupported ovhtypes.TfBoolValue   `tfsdk:"is_supported" json:"isSupported"`
	RetentionId ovhtypes.TfStringValue `tfsdk:"retention_id" json:"retentionId"`
	ServiceName ovhtypes.TfStringValue `tfsdk:"service_name" json:"serviceName"`
}

func (v *DbaasLogsClusterRetentionModel) MergeWith(other *DbaasLogsClusterRetentionModel) {
	if (v.ClusterId.IsUnknown() || v.ClusterId.IsNull()) && !other.ClusterId.IsUnknown() {
		v.ClusterId = other.ClusterId
	}

	if (v.Duration.IsUnknown() || v.Duration.IsNull()) && !other.Duration.IsUnknown() {
		v.Duration = other.Duration
	}

	if (v.IsSupported.IsUnknown() || v.IsSupported.IsNull()) && !other.IsSupported.IsUnknown() {
		v.IsSupported = other.IsSupported
	}

	if (v.RetentionId.IsUnknown() || v.RetentionId.IsNull()) && !other.RetentionId.IsUnknown() {
		v.RetentionId = other.RetentionId
	}

	if (v.ServiceName.IsUnknown() || v.ServiceName.IsNull()) && !other.ServiceName.IsUnknown() {
		v.ServiceName = other.ServiceName
	}
}
