// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package ovh

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ovhtypes "github.com/ovh/terraform-provider-ovh/v2/ovh/types"
)

func CloudProjectStorageLifecycleConfigurationDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				CustomType:  ovhtypes.TfStringType{},
				Computed:    true,
				Description: "Unique identifier for the resource (service_name/region_name/container_name)",
			},
			"service_name": schema.StringAttribute{
				CustomType:          ovhtypes.TfStringType{},
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the public cloud project.",
				MarkdownDescription: "The ID of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.",
			},
			"region_name": schema.StringAttribute{
				CustomType:          ovhtypes.TfStringType{},
				Required:            true,
				Description:         "Region name of the storage container.",
				MarkdownDescription: "Region name of the storage container.",
			},
			"container_name": schema.StringAttribute{
				CustomType:          ovhtypes.TfStringType{},
				Required:            true,
				Description:         "Name of the storage container.",
				MarkdownDescription: "Name of the storage container.",
			},
			"rules": schema.ListNestedAttribute{
				CustomType: ovhtypes.NewTfListNestedType[LifecycleRuleValue](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							CustomType:          ovhtypes.TfStringType{},
							Computed:            true,
							Description:         "Rule ID.",
							MarkdownDescription: "Rule ID.",
						},
						"status": schema.StringAttribute{
							CustomType:          ovhtypes.TfStringType{},
							Computed:            true,
							Description:         "Rule status.",
							MarkdownDescription: "Rule status.",
							Validators: []validator.String{
								stringvalidator.OneOf("enabled", "disabled"),
							},
						},
						"filter": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"prefix": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "Prefix filter.",
									MarkdownDescription: "Prefix filter.",
								},
								"object_size_greater_than": schema.Int64Attribute{
									CustomType:          ovhtypes.TfInt64Type{},
									Computed:            true,
									Description:         "Minimum object size in bytes to which the rule applies.",
									MarkdownDescription: "Minimum object size in bytes to which the rule applies.",
								},
								"object_size_less_than": schema.Int64Attribute{
									CustomType:          ovhtypes.TfInt64Type{},
									Computed:            true,
									Description:         "Maximum object size in bytes to which the rule applies.",
									MarkdownDescription: "Maximum object size in bytes to which the rule applies.",
								},
								"tags": schema.MapAttribute{
									CustomType:          ovhtypes.NewTfMapNestedType[ovhtypes.TfStringValue](ctx),
									Computed:            true,
									Description:         "Tags filter.",
									MarkdownDescription: "Tags filter.",
								},
							},
							CustomType: LifecycleRuleFilterType{
								ObjectType: types.ObjectType{
									AttrTypes: LifecycleRuleFilterValue{}.AttributeTypes(ctx),
								},
							},
							Computed:            true,
							Description:         "Rule filters.",
							MarkdownDescription: "Rule filters.",
						},
						"expiration": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"days": schema.Int64Attribute{
									CustomType:          ovhtypes.TfInt64Type{},
									Computed:            true,
									Description:         "Objects will be deleted past this lifetime (in days).",
									MarkdownDescription: "Objects will be deleted past this lifetime (in days).",
								},
								"date": schema.StringAttribute{
									CustomType:          ovhtypes.TfStringType{},
									Computed:            true,
									Description:         "Indicates at what date the objects will be deleted (YYYY-MM-DD).",
									MarkdownDescription: "Indicates at what date the objects will be deleted (YYYY-MM-DD).",
								},
								"expired_object_delete_marker": schema.BoolAttribute{
									CustomType:          ovhtypes.TfBoolType{},
									Computed:            true,
									Description:         "Indicates whether a delete marker with no noncurrent versions will be removed.",
									MarkdownDescription: "Indicates whether a delete marker with no noncurrent versions will be removed.",
								},
							},
							CustomType: LifecycleRuleExpirationFilterType{
								ObjectType: types.ObjectType{
									AttrTypes: LifecycleRuleExpirationValue{}.AttributeTypes(ctx),
								},
							},
							Computed:            true,
							Description:         "Lifecycle rule expiration configuration.",
							MarkdownDescription: "Lifecycle rule expiration configuration.",
						},
						"abort_incomplete_multipart_upload": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"days_after_initiation": schema.Int64Attribute{
									CustomType:          ovhtypes.TfInt64Type{},
									Computed:            true,
									Description:         "Specifies the number of days after which an incomplete multipart upload is aborted.",
									MarkdownDescription: "Specifies the number of days after which an incomplete multipart upload is aborted.",
								},
							},
							CustomType: LifecycleRuleAbortIncompleteMultipartUploadType{
								ObjectType: types.ObjectType{
									AttrTypes: LifecycleRuleAbortIncompleteMultipartUploadValue{}.AttributeTypes(ctx),
								},
							},
							Computed:            true,
							Description:         "Abort incomplete multipart upload configuration.",
							MarkdownDescription: "Abort incomplete multipart upload configuration.",
						},
						"noncurrent_version_expiration": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"noncurrent_days": schema.Int64Attribute{
									CustomType:          ovhtypes.TfInt64Type{},
									Computed:            true,
									Description:         "Specifies the number of days an object is noncurrent before it can be expired.",
									MarkdownDescription: "Specifies the number of days an object is noncurrent before it can be expired.",
								},
								"newer_noncurrent_versions": schema.Int64Attribute{
									CustomType:          ovhtypes.TfInt64Type{},
									Computed:            true,
									Description:         "Specifies how many noncurrent versions to retain.",
									MarkdownDescription: "Specifies how many noncurrent versions to retain.",
								},
							},
							CustomType: LifecycleRuleNoncurrentVersionExpirationType{
								ObjectType: types.ObjectType{
									AttrTypes: LifecycleRuleNoncurrentVersionExpirationValue{}.AttributeTypes(ctx),
								},
							},
							Computed:            true,
							Description:         "Specifies when noncurrent object versions expire.",
							MarkdownDescription: "Specifies when noncurrent object versions expire.",
						},
						"transitions": schema.ListNestedAttribute{
							CustomType: ovhtypes.NewTfListNestedType[LifecycleRuleTransitionValue](ctx),
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"days": schema.Int64Attribute{
										CustomType:          ovhtypes.TfInt64Type{},
										Computed:            true,
										Description:         "Indicates the number of days after creation when objects are transitioned.",
										MarkdownDescription: "Indicates the number of days after creation when objects are transitioned.",
									},
									"date": schema.StringAttribute{
										CustomType:          ovhtypes.TfStringType{},
										Computed:            true,
										Description:         "Indicates when objects are transitioned to the specified storage class (YYYY-MM-DD).",
										MarkdownDescription: "Indicates when objects are transitioned to the specified storage class (YYYY-MM-DD).",
									},
									"storage_class": schema.StringAttribute{
										CustomType:          ovhtypes.TfStringType{},
										Computed:            true,
										Description:         "The storage class to which you want the object to transition.",
										MarkdownDescription: "The storage class to which you want the object to transition.",
									},
								},
								CustomType: LifecycleRuleTransitionType{
									ObjectType: types.ObjectType{
										AttrTypes: LifecycleRuleTransitionValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "Specifies when an object transitions to a specified storage class.",
							MarkdownDescription: "Specifies when an object transitions to a specified storage class.",
						},
						"noncurrent_version_transitions": schema.ListNestedAttribute{
							CustomType: ovhtypes.NewTfListNestedType[LifecycleRuleNoncurrentVersionTransitionValue](ctx),
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"noncurrent_days": schema.Int64Attribute{
										CustomType:          ovhtypes.TfInt64Type{},
										Computed:            true,
										Description:         "Specifies the number of days an object is noncurrent before the transition.",
										MarkdownDescription: "Specifies the number of days an object is noncurrent before the transition.",
									},
									"newer_noncurrent_versions": schema.Int64Attribute{
										CustomType:          ovhtypes.TfInt64Type{},
										Computed:            true,
										Description:         "Specifies how many noncurrent versions to retain in the same storage class.",
										MarkdownDescription: "Specifies how many noncurrent versions to retain in the same storage class.",
									},
									"storage_class": schema.StringAttribute{
										CustomType:          ovhtypes.TfStringType{},
										Computed:            true,
										Description:         "The storage class to which you want the noncurrent object to transition.",
										MarkdownDescription: "The storage class to which you want the noncurrent object to transition.",
									},
								},
								CustomType: LifecycleRuleNoncurrentVersionTransitionType{
									ObjectType: types.ObjectType{
										AttrTypes: LifecycleRuleNoncurrentVersionTransitionValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "Specifies the transition rule for noncurrent object versions.",
							MarkdownDescription: "Specifies the transition rule for noncurrent object versions.",
						},
					},
					CustomType: LifecycleRuleType{
						ObjectType: types.ObjectType{
							AttrTypes: LifecycleRuleValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "List of lifecycle rules.",
				MarkdownDescription: "List of lifecycle rules.",
			},
		},
		Description:         "Get S3-compatible storage container lifecycle configuration.",
		MarkdownDescription: "Get S3-compatible storage container lifecycle configuration for an OVHcloud Object Storage bucket.",
	}
}
