// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package ovh

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	ovhtypes "github.com/ovh/terraform-provider-ovh/v2/ovh/types"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func VpsReinstallResourceSchema(ctx context.Context) schema.Schema {
	attrs := map[string]schema.Attribute{
		"cluster": schema.StringAttribute{
			CustomType: ovhtypes.TfStringType{},
			Computed:   true,
		},
		"date": schema.StringAttribute{
			CustomType: ovhtypes.TfStringType{},
			Computed:   true,
		},
		"display_name": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Set the name displayed in ManagerV6 for your VPS (max 50 chars)",
			MarkdownDescription: "Set the name displayed in ManagerV6 for your VPS (max 50 chars)",
		},
		"do_not_send_password": schema.BoolAttribute{
			CustomType:          ovhtypes.TfBoolType{},
			Optional:            true,
			Computed:            true,
			Description:         "If asked, the installation password will NOT be sent (only if sshKey defined)",
			MarkdownDescription: "If asked, the installation password will NOT be sent (only if sshKey defined)",
		},
		"iam": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"display_name": schema.StringAttribute{
					CustomType:          ovhtypes.TfStringType{},
					Computed:            true,
					Description:         "Resource display name",
					MarkdownDescription: "Resource display name",
				},
				"id": schema.StringAttribute{
					CustomType:          ovhtypes.TfStringType{},
					Computed:            true,
					Description:         "Unique identifier of the resource",
					MarkdownDescription: "Unique identifier of the resource",
				},
				"tags": schema.MapAttribute{
					CustomType:          ovhtypes.NewTfMapNestedType[ovhtypes.TfStringValue](ctx),
					Computed:            true,
					Description:         "Resource tags. Tags that were internally computed are prefixed with ovh:",
					MarkdownDescription: "Resource tags. Tags that were internally computed are prefixed with ovh:",
				},
				"urn": schema.StringAttribute{
					CustomType:          ovhtypes.TfStringType{},
					Computed:            true,
					Description:         "Unique resource name used in policies",
					MarkdownDescription: "Unique resource name used in policies",
				},
			},
			CustomType: IamType{
				ObjectType: types.ObjectType{
					AttrTypes: IamValue{}.AttributeTypes(ctx),
				},
			},
			Computed:            true,
			Description:         "IAM resource metadata",
			MarkdownDescription: "IAM resource metadata",
		},
		"id": schema.Int64Attribute{
			CustomType: ovhtypes.TfInt64Type{},
			Computed:   true,
		},
		"image_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Id of the vps.Image fetched in /images list",
			MarkdownDescription: "Id of the vps.Image fetched in /images list",
		},
		"install_rtm": schema.BoolAttribute{
			CustomType:          ovhtypes.TfBoolType{},
			Optional:            true,
			Computed:            true,
			Description:         "If asked, RTM will be installed on your VPS",
			MarkdownDescription: "If asked, RTM will be installed on your VPS",
		},
		"keymap": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Set KVM keyboard layout on VPS Cloud. Reboot your VPS after change",
			MarkdownDescription: "Set KVM keyboard layout on VPS Cloud. Reboot your VPS after change",
		},
		"lock_status": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"locked": schema.BoolAttribute{
					CustomType:          ovhtypes.TfBoolType{},
					Computed:            true,
					Description:         "Indicates whether the VPS is locked",
					MarkdownDescription: "Indicates whether the VPS is locked",
				},
				"reason": schema.StringAttribute{
					CustomType:          ovhtypes.TfStringType{},
					Computed:            true,
					Description:         "The reason for the lock",
					MarkdownDescription: "The reason for the lock",
				},
			},
			CustomType: LockStatusType{
				ObjectType: types.ObjectType{
					AttrTypes: LockStatusValue{}.AttributeTypes(ctx),
				},
			},
			Computed:            true,
			Description:         "Lock status of the VPS",
			MarkdownDescription: "Lock status of the VPS",
		},
		"memory_limit": schema.Int64Attribute{
			CustomType: ovhtypes.TfInt64Type{},
			Computed:   true,
		},
		"model": schema.SingleNestedAttribute{
			Attributes: map[string]schema.Attribute{
				"available_options": schema.ListAttribute{
					CustomType: ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
					Computed:   true,
				},
				"datacenter": schema.ListAttribute{
					CustomType: ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
					Computed:   true,
				},
				"disk": schema.Int64Attribute{
					CustomType: ovhtypes.TfInt64Type{},
					Computed:   true,
				},
				"maximum_additionnal_ip": schema.Int64Attribute{
					CustomType: ovhtypes.TfInt64Type{},
					Computed:   true,
				},
				"memory": schema.Int64Attribute{
					CustomType: ovhtypes.TfInt64Type{},
					Computed:   true,
				},
				"name": schema.StringAttribute{
					CustomType: ovhtypes.TfStringType{},
					Computed:   true,
				},
				"offer": schema.StringAttribute{
					CustomType: ovhtypes.TfStringType{},
					Computed:   true,
				},
				"vcore": schema.Int64Attribute{
					CustomType: ovhtypes.TfInt64Type{},
					Computed:   true,
				},
				"version": schema.StringAttribute{
					CustomType:          ovhtypes.TfStringType{},
					Computed:            true,
					Description:         "All versions that VPS can have",
					MarkdownDescription: "All versions that VPS can have",
				},
			},
			CustomType: ModelType{
				ObjectType: types.ObjectType{
					AttrTypes: ModelValue{}.AttributeTypes(ctx),
				},
			},
			Computed:            true,
			Description:         "A structure describing characteristics of a VPS model",
			MarkdownDescription: "A structure describing characteristics of a VPS model",
		},
		"monitoring_ip_blocks": schema.ListAttribute{
			CustomType:          ovhtypes.NewTfListNestedType[ovhtypes.TfStringValue](ctx),
			Computed:            true,
			Description:         "Ip blocks for OVH monitoring servers",
			MarkdownDescription: "Ip blocks for OVH monitoring servers",
		},
		"name": schema.StringAttribute{
			CustomType: ovhtypes.TfStringType{},
			Computed:   true,
		},
		"netboot_mode": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "All values a VPS netboot mode can be in",
			MarkdownDescription: "All values a VPS netboot mode can be in",
		},
		"offer_type": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "All offers a VPS can have",
			MarkdownDescription: "All offers a VPS can have",
		},
		"progress": schema.Int64Attribute{
			CustomType: ovhtypes.TfInt64Type{},
			Computed:   true,
		},
		"public_ssh_key": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "Public SSH key to pre-install on your VPS",
			MarkdownDescription: "Public SSH key to pre-install on your VPS",
		},
		"service_name": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Service name",
			MarkdownDescription: "Service name",
		},
		"sla_monitoring": schema.BoolAttribute{
			CustomType: ovhtypes.TfBoolType{},
			Computed:   true,
		},
		"ssh_key": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "SSH key name to pre-install on your VPS (name from /me/sshKey)",
			MarkdownDescription: "SSH key name to pre-install on your VPS (name from /me/sshKey)",
		},
		"state": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "All states a VPS task can be in",
			MarkdownDescription: "All states a VPS task can be in",
		},
		"type": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "All type a VPS task can be",
			MarkdownDescription: "All type a VPS task can be",
		},
		"vcore": schema.Int64Attribute{
			CustomType: ovhtypes.TfInt64Type{},
			Computed:   true,
		},
		"zone": schema.StringAttribute{
			CustomType: ovhtypes.TfStringType{},
			Computed:   true,
		},
		"zone_type": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Enum values for zone type",
			MarkdownDescription: "Enum values for zone type",
		},
	}

	return schema.Schema{
		Description: "",
		Attributes:  attrs,
	}
}

type VpsReinstallModel struct {
	Cluster            ovhtypes.TfStringValue                             `tfsdk:"cluster" json:"cluster"`
	Date               ovhtypes.TfStringValue                             `tfsdk:"date" json:"date"`
	DisplayName        ovhtypes.TfStringValue                             `tfsdk:"display_name" json:"displayName"`
	DoNotSendPassword  ovhtypes.TfBoolValue                               `tfsdk:"do_not_send_password" json:"doNotSendPassword"`
	Iam                IamValue                                           `tfsdk:"iam" json:"iam"`
	Id                 ovhtypes.TfInt64Value                              `tfsdk:"id" json:"id"`
	ImageId            ovhtypes.TfStringValue                             `tfsdk:"image_id" json:"imageId"`
	InstallRtm         ovhtypes.TfBoolValue                               `tfsdk:"install_rtm" json:"installRtm"`
	Keymap             ovhtypes.TfStringValue                             `tfsdk:"keymap" json:"keymap"`
	LockStatus         LockStatusValue                                    `tfsdk:"lock_status" json:"lockStatus"`
	MemoryLimit        ovhtypes.TfInt64Value                              `tfsdk:"memory_limit" json:"memoryLimit"`
	Model              ModelValue                                         `tfsdk:"model" json:"model"`
	MonitoringIpBlocks ovhtypes.TfListNestedValue[ovhtypes.TfStringValue] `tfsdk:"monitoring_ip_blocks" json:"monitoringIpBlocks"`
	Name               ovhtypes.TfStringValue                             `tfsdk:"name" json:"name"`
	NetbootMode        ovhtypes.TfStringValue                             `tfsdk:"netboot_mode" json:"netbootMode"`
	OfferType          ovhtypes.TfStringValue                             `tfsdk:"offer_type" json:"offerType"`
	Progress           ovhtypes.TfInt64Value                              `tfsdk:"progress" json:"progress"`
	PublicSshKey       ovhtypes.TfStringValue                             `tfsdk:"public_ssh_key" json:"publicSshKey"`
	ServiceName        ovhtypes.TfStringValue                             `tfsdk:"service_name" json:"serviceName"`
	SlaMonitoring      ovhtypes.TfBoolValue                               `tfsdk:"sla_monitoring" json:"slaMonitoring"`
	SshKey             ovhtypes.TfStringValue                             `tfsdk:"ssh_key" json:"sshKey"`
	State              ovhtypes.TfStringValue                             `tfsdk:"state" json:"state"`
	Type               ovhtypes.TfStringValue                             `tfsdk:"type" json:"type"`
	Vcore              ovhtypes.TfInt64Value                              `tfsdk:"vcore" json:"vcore"`
	Zone               ovhtypes.TfStringValue                             `tfsdk:"zone" json:"zone"`
	ZoneType           ovhtypes.TfStringValue                             `tfsdk:"zone_type" json:"zoneType"`
}

func (v *VpsReinstallModel) MergeWith(other *VpsReinstallModel) {

	if (v.Cluster.IsUnknown() || v.Cluster.IsNull()) && !other.Cluster.IsUnknown() {
		v.Cluster = other.Cluster
	}

	if (v.Date.IsUnknown() || v.Date.IsNull()) && !other.Date.IsUnknown() {
		v.Date = other.Date
	}

	if (v.DisplayName.IsUnknown() || v.DisplayName.IsNull()) && !other.DisplayName.IsUnknown() {
		v.DisplayName = other.DisplayName
	}

	if (v.DoNotSendPassword.IsUnknown() || v.DoNotSendPassword.IsNull()) && !other.DoNotSendPassword.IsUnknown() {
		v.DoNotSendPassword = other.DoNotSendPassword
	}

	if (v.Iam.IsUnknown() || v.Iam.IsNull()) && !other.Iam.IsUnknown() {
		v.Iam = other.Iam
	}

	if (v.Id.IsUnknown() || v.Id.IsNull()) && !other.Id.IsUnknown() {
		v.Id = other.Id
	}

	if (v.ImageId.IsUnknown() || v.ImageId.IsNull()) && !other.ImageId.IsUnknown() {
		v.ImageId = other.ImageId
	}

	if (v.InstallRtm.IsUnknown() || v.InstallRtm.IsNull()) && !other.InstallRtm.IsUnknown() {
		v.InstallRtm = other.InstallRtm
	}

	if (v.Keymap.IsUnknown() || v.Keymap.IsNull()) && !other.Keymap.IsUnknown() {
		v.Keymap = other.Keymap
	}

	if (v.LockStatus.IsUnknown() || v.LockStatus.IsNull()) && !other.LockStatus.IsUnknown() {
		v.LockStatus = other.LockStatus
	}

	if (v.MemoryLimit.IsUnknown() || v.MemoryLimit.IsNull()) && !other.MemoryLimit.IsUnknown() {
		v.MemoryLimit = other.MemoryLimit
	}

	if (v.Model.IsUnknown() || v.Model.IsNull()) && !other.Model.IsUnknown() {
		v.Model = other.Model
	}

	if (v.MonitoringIpBlocks.IsUnknown() || v.MonitoringIpBlocks.IsNull()) && !other.MonitoringIpBlocks.IsUnknown() {
		v.MonitoringIpBlocks = other.MonitoringIpBlocks
	}

	if (v.Name.IsUnknown() || v.Name.IsNull()) && !other.Name.IsUnknown() {
		v.Name = other.Name
	}

	if (v.NetbootMode.IsUnknown() || v.NetbootMode.IsNull()) && !other.NetbootMode.IsUnknown() {
		v.NetbootMode = other.NetbootMode
	}

	if (v.OfferType.IsUnknown() || v.OfferType.IsNull()) && !other.OfferType.IsUnknown() {
		v.OfferType = other.OfferType
	}

	if (v.Progress.IsUnknown() || v.Progress.IsNull()) && !other.Progress.IsUnknown() {
		v.Progress = other.Progress
	}

	if (v.PublicSshKey.IsUnknown() || v.PublicSshKey.IsNull()) && !other.PublicSshKey.IsUnknown() {
		v.PublicSshKey = other.PublicSshKey
	}

	if (v.ServiceName.IsUnknown() || v.ServiceName.IsNull()) && !other.ServiceName.IsUnknown() {
		v.ServiceName = other.ServiceName
	}

	if (v.SlaMonitoring.IsUnknown() || v.SlaMonitoring.IsNull()) && !other.SlaMonitoring.IsUnknown() {
		v.SlaMonitoring = other.SlaMonitoring
	}

	if (v.SshKey.IsUnknown() || v.SshKey.IsNull()) && !other.SshKey.IsUnknown() {
		v.SshKey = other.SshKey
	}

	if (v.State.IsUnknown() || v.State.IsNull()) && !other.State.IsUnknown() {
		v.State = other.State
	}

	if (v.Type.IsUnknown() || v.Type.IsNull()) && !other.Type.IsUnknown() {
		v.Type = other.Type
	}

	if (v.Vcore.IsUnknown() || v.Vcore.IsNull()) && !other.Vcore.IsUnknown() {
		v.Vcore = other.Vcore
	}

	if (v.Zone.IsUnknown() || v.Zone.IsNull()) && !other.Zone.IsUnknown() {
		v.Zone = other.Zone
	}

	if (v.ZoneType.IsUnknown() || v.ZoneType.IsNull()) && !other.ZoneType.IsUnknown() {
		v.ZoneType = other.ZoneType
	}

}

func (v VpsReinstallModel) ToCreate() *VpsReinstallModel {
	res := &VpsReinstallModel{}

	if !v.DoNotSendPassword.IsUnknown() {
		res.DoNotSendPassword = v.DoNotSendPassword
	}

	if !v.ImageId.IsUnknown() {
		res.ImageId = v.ImageId
	}

	if !v.InstallRtm.IsUnknown() {
		res.InstallRtm = v.InstallRtm
	}

	if !v.PublicSshKey.IsUnknown() {
		res.PublicSshKey = v.PublicSshKey
	}

	if !v.SshKey.IsUnknown() {
		res.SshKey = v.SshKey
	}

	return res
}

func (v VpsReinstallModel) ToUpdate() *VpsReinstallModel {
	res := &VpsReinstallModel{}

	if !v.DisplayName.IsUnknown() {
		res.DisplayName = v.DisplayName
	}

	if !v.Keymap.IsUnknown() {
		res.Keymap = v.Keymap
	}

	if !v.NetbootMode.IsUnknown() {
		res.NetbootMode = v.NetbootMode
	}

	return res
}

func (v *VpsReinstallModel) MarshalJSON() ([]byte, error) {
	toMarshal := map[string]any{}
	if !v.DisplayName.IsNull() && !v.DisplayName.IsUnknown() {
		toMarshal["displayName"] = v.DisplayName
	}
	if !v.DoNotSendPassword.IsNull() && !v.DoNotSendPassword.IsUnknown() {
		toMarshal["doNotSendPassword"] = v.DoNotSendPassword
	}
	if !v.ImageId.IsNull() && !v.ImageId.IsUnknown() {
		toMarshal["imageId"] = v.ImageId
	}
	if !v.InstallRtm.IsNull() && !v.InstallRtm.IsUnknown() {
		toMarshal["installRtm"] = v.InstallRtm
	}
	if !v.Keymap.IsNull() && !v.Keymap.IsUnknown() {
		toMarshal["keymap"] = v.Keymap
	}
	if !v.NetbootMode.IsNull() && !v.NetbootMode.IsUnknown() {
		toMarshal["netbootMode"] = v.NetbootMode
	}
	if !v.PublicSshKey.IsNull() && !v.PublicSshKey.IsUnknown() {
		toMarshal["publicSshKey"] = v.PublicSshKey
	}
	if !v.SshKey.IsNull() && !v.SshKey.IsUnknown() {
		toMarshal["sshKey"] = v.SshKey
	}

	return json.Marshal(toMarshal)
}

var _ basetypes.ObjectTypable = IamType{}

var _ basetypes.ObjectValuable = IamValue{}

var _ basetypes.ObjectTypable = LockStatusType{}

type LockStatusType struct {
	basetypes.ObjectType
}

func (t LockStatusType) Equal(o attr.Type) bool {
	other, ok := o.(LockStatusType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LockStatusType) String() string {
	return "LockStatusType"
}

func (t LockStatusType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	lockedAttribute, ok := attributes["locked"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`locked is missing from object`)

		return nil, diags
	}

	lockedVal, ok := lockedAttribute.(ovhtypes.TfBoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`locked expected to be ovhtypes.TfBoolValue, was: %T`, lockedAttribute))
	}

	reasonAttribute, ok := attributes["reason"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`reason is missing from object`)

		return nil, diags
	}

	reasonVal, ok := reasonAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`reason expected to be ovhtypes.TfStringValue, was: %T`, reasonAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return LockStatusValue{
		Locked: lockedVal,
		Reason: reasonVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewLockStatusValueNull() LockStatusValue {
	return LockStatusValue{
		state: attr.ValueStateNull,
	}
}

func NewLockStatusValueUnknown() LockStatusValue {
	return LockStatusValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLockStatusValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LockStatusValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LockStatusValue Attribute Value",
				"While creating a LockStatusValue value, a missing attribute value was detected. "+
					"A LockStatusValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LockStatusValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LockStatusValue Attribute Type",
				"While creating a LockStatusValue value, an invalid attribute value was detected. "+
					"A LockStatusValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LockStatusValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LockStatusValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LockStatusValue Attribute Value",
				"While creating a LockStatusValue value, an extra attribute value was detected. "+
					"A LockStatusValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LockStatusValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLockStatusValueUnknown(), diags
	}

	lockedAttribute, ok := attributes["locked"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`locked is missing from object`)

		return NewLockStatusValueUnknown(), diags
	}

	lockedVal, ok := lockedAttribute.(ovhtypes.TfBoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`locked expected to be ovhtypes.TfBoolValue, was: %T`, lockedAttribute))
	}

	reasonAttribute, ok := attributes["reason"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`reason is missing from object`)

		return NewLockStatusValueUnknown(), diags
	}

	reasonVal, ok := reasonAttribute.(ovhtypes.TfStringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`reason expected to be ovhtypes.TfStringValue, was: %T`, reasonAttribute))
	}

	if diags.HasError() {
		return NewLockStatusValueUnknown(), diags
	}

	return LockStatusValue{
		Locked: lockedVal,
		Reason: reasonVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewLockStatusValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LockStatusValue {
	object, diags := NewLockStatusValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLockStatusValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LockStatusType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLockStatusValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLockStatusValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLockStatusValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLockStatusValueMust(LockStatusValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LockStatusType) ValueType(ctx context.Context) attr.Value {
	return LockStatusValue{}
}

var _ basetypes.ObjectValuable = LockStatusValue{}

type LockStatusValue struct {
	Locked ovhtypes.TfBoolValue   `tfsdk:"locked" json:"locked"`
	Reason ovhtypes.TfStringValue `tfsdk:"reason" json:"reason"`
	state  attr.ValueState
}

func (v LockStatusValue) ToCreate() *LockStatusValue {
	res := &LockStatusValue{}

	if !v.Reason.IsNull() {
		res.Reason = v.Reason
	}

	if !v.Locked.IsNull() {
		res.Locked = v.Locked
	}

	res.state = attr.ValueStateKnown

	return res
}

func (v LockStatusValue) MarshalJSON() ([]byte, error) {
	toMarshal := map[string]any{}
	if !v.Locked.IsNull() && !v.Locked.IsUnknown() {
		toMarshal["locked"] = v.Locked
	}
	if !v.Reason.IsNull() && !v.Reason.IsUnknown() {
		toMarshal["reason"] = v.Reason
	}

	return json.Marshal(toMarshal)
}

func (v *LockStatusValue) UnmarshalJSON(data []byte) error {
	type JsonLockStatusValue LockStatusValue

	var tmp JsonLockStatusValue
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}
	v.Locked = tmp.Locked
	v.Reason = tmp.Reason

	v.state = attr.ValueStateKnown

	return nil
}

func (v *LockStatusValue) MergeWith(other *LockStatusValue) {

	if (v.Locked.IsUnknown() || v.Locked.IsNull()) && !other.Locked.IsUnknown() {
		v.Locked = other.Locked
	}

	if (v.Reason.IsUnknown() || v.Reason.IsNull()) && !other.Reason.IsUnknown() {
		v.Reason = other.Reason
	}

	if (v.state == attr.ValueStateUnknown || v.state == attr.ValueStateNull) && other.state != attr.ValueStateUnknown {
		v.state = other.state
	}
}

func (v LockStatusValue) Attributes() map[string]attr.Value {
	return map[string]attr.Value{
		"locked": v.Locked,
		"reason": v.Reason,
	}
}
func (v LockStatusValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["locked"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["reason"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Locked.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["locked"] = val

		val, err = v.Reason.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["reason"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LockStatusValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LockStatusValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LockStatusValue) String() string {
	return "LockStatusValue"
}

func (v LockStatusValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"locked": ovhtypes.TfBoolType{},
			"reason": ovhtypes.TfStringType{},
		},
		map[string]attr.Value{
			"locked": v.Locked,
			"reason": v.Reason,
		})

	return objVal, diags
}

func (v LockStatusValue) Equal(o attr.Value) bool {
	other, ok := o.(LockStatusValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Locked.Equal(other.Locked) {
		return false
	}

	if !v.Reason.Equal(other.Reason) {
		return false
	}

	return true
}

func (v LockStatusValue) Type(ctx context.Context) attr.Type {
	return LockStatusType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LockStatusValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"locked": ovhtypes.TfBoolType{},
		"reason": ovhtypes.TfStringType{},
	}
}

var _ basetypes.ObjectTypable = ModelType{}
var _ basetypes.ObjectValuable = ModelValue{}

func (v ModelValue) ToCreate() *ModelValue {
	res := &ModelValue{}

	if !v.AvailableOptions.IsNull() {
		res.AvailableOptions = v.AvailableOptions
	}

	if !v.Vcore.IsNull() {
		res.Vcore = v.Vcore
	}

	if !v.Datacenter.IsNull() {
		res.Datacenter = v.Datacenter
	}

	if !v.Offer.IsNull() {
		res.Offer = v.Offer
	}

	if !v.Version.IsNull() {
		res.Version = v.Version
	}

	if !v.Name.IsNull() {
		res.Name = v.Name
	}

	if !v.MaximumAdditionnalIp.IsNull() {
		res.MaximumAdditionnalIp = v.MaximumAdditionnalIp
	}

	if !v.Memory.IsNull() {
		res.Memory = v.Memory
	}

	if !v.Disk.IsNull() {
		res.Disk = v.Disk
	}

	res.state = attr.ValueStateKnown

	return res
}

func (v ModelValue) MarshalJSON() ([]byte, error) {
	toMarshal := map[string]any{}
	if !v.AvailableOptions.IsNull() && !v.AvailableOptions.IsUnknown() {
		toMarshal["availableOptions"] = v.AvailableOptions
	}
	if !v.Datacenter.IsNull() && !v.Datacenter.IsUnknown() {
		toMarshal["datacenter"] = v.Datacenter
	}
	if !v.Disk.IsNull() && !v.Disk.IsUnknown() {
		toMarshal["disk"] = v.Disk
	}
	if !v.MaximumAdditionnalIp.IsNull() && !v.MaximumAdditionnalIp.IsUnknown() {
		toMarshal["maximumAdditionnalIp"] = v.MaximumAdditionnalIp
	}
	if !v.Memory.IsNull() && !v.Memory.IsUnknown() {
		toMarshal["memory"] = v.Memory
	}
	if !v.Name.IsNull() && !v.Name.IsUnknown() {
		toMarshal["name"] = v.Name
	}
	if !v.Offer.IsNull() && !v.Offer.IsUnknown() {
		toMarshal["offer"] = v.Offer
	}
	if !v.Vcore.IsNull() && !v.Vcore.IsUnknown() {
		toMarshal["vcore"] = v.Vcore
	}
	if !v.Version.IsNull() && !v.Version.IsUnknown() {
		toMarshal["version"] = v.Version
	}

	return json.Marshal(toMarshal)
}
