package ovh

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/ovh/terraform-provider-ovh/v2/ovh/helpers"
	"github.com/ovh/terraform-provider-ovh/v2/ovh/ovhwrap"
)

func resourceDedicatedServerVirtualMac() *schema.Resource {
	return &schema.Resource{
		Create: resourceDedicatedServerVirtualMacCreate,
		Read:   resourceDedicatedServerVirtualMacRead,
		Delete: resourceDedicatedServerVirtualMacDelete,
		Importer: &schema.ResourceImporter{
			State: resourceDedicatedServerVirtualMacImportState,
		},

		Schema: map[string]*schema.Schema{
			"service_name": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The internal name of your dedicated server.",
			},
			"ip_address": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The additional IP address to attach to the virtual MAC.",
			},
			"type": {
				Type:         schema.TypeString,
				Optional:     true,
				ForceNew:     true,
				Default:      "ovh",
				ValidateFunc: helpers.ValidateEnum([]string{"ovh", "vmware"}),
				Description:  "The type of the virtual MAC address (ovh or vmware).",
			},
			"virtual_machine_name": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "A human-readable name to identify the IP/MAC pair.",
			},

			// Computed
			"mac_address": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The virtual MAC address generated by OVHcloud.",
			},
		},
	}
}

func resourceDedicatedServerVirtualMacCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)
	serviceName := d.Get("service_name").(string)
	ipAddress := d.Get("ip_address").(string)

	opts := &DedicatedServerVirtualMacCreateOpts{
		IPAddress:          ipAddress,
		Type:               d.Get("type").(string),
		VirtualMachineName: d.Get("virtual_machine_name").(string),
	}

	endpoint := fmt.Sprintf("/dedicated/server/%s/virtualMac", url.PathEscape(serviceName))

	task := &DedicatedServerTask{}
	if err := config.OVHClient.Post(endpoint, opts, task); err != nil {
		return fmt.Errorf("Error calling POST %s with opts %v:\n\t %q", endpoint, opts, err)
	}

	if err := waitForDedicatedServerTask(serviceName, task, config.OVHClient); err != nil {
		return fmt.Errorf("Error waiting for virtual MAC creation on %s for IP %s: %s", serviceName, ipAddress, err)
	}

	// OVHcloud generates the MAC address, so it has to be discovered by finding
	// which virtual MAC now carries our IP once the creation task is done.
	mac, err := dedicatedServerVirtualMacForIP(serviceName, ipAddress, config.OVHClient)
	if err != nil {
		return err
	}
	if mac == "" {
		return fmt.Errorf("Virtual MAC creation task on %s completed but no MAC carries IP %s", serviceName, ipAddress)
	}

	d.SetId(fmt.Sprintf("%s/%s/%s", serviceName, mac, ipAddress))

	return resourceDedicatedServerVirtualMacRead(d, meta)
}

func resourceDedicatedServerVirtualMacRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	serviceName, mac, ipAddress, err := dedicatedServerVirtualMacSplitId(d.Id())
	if err != nil {
		return err
	}

	managementEndpoint := fmt.Sprintf("/dedicated/server/%s/virtualMac/%s/virtualAddress/%s",
		url.PathEscape(serviceName),
		url.PathEscape(mac),
		url.PathEscape(ipAddress),
	)
	management := &DedicatedServerVirtualMacManagement{}
	if err := config.OVHClient.Get(managementEndpoint, management); err != nil {
		return helpers.CheckDeleted(d, err, managementEndpoint)
	}

	vmac := &DedicatedServerVirtualMac{}
	vmacEndpoint := fmt.Sprintf("/dedicated/server/%s/virtualMac/%s",
		url.PathEscape(serviceName),
		url.PathEscape(mac),
	)
	if err := config.OVHClient.Get(vmacEndpoint, vmac); err != nil {
		return helpers.CheckDeleted(d, err, vmacEndpoint)
	}

	d.Set("service_name", serviceName)
	d.Set("ip_address", management.IPAddress)
	d.Set("virtual_machine_name", management.VirtualMachineName)
	d.Set("type", vmac.Type)
	d.Set("mac_address", mac)

	return nil
}

func resourceDedicatedServerVirtualMacDelete(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	serviceName, mac, ipAddress, err := dedicatedServerVirtualMacSplitId(d.Id())
	if err != nil {
		return err
	}

	endpoint := fmt.Sprintf("/dedicated/server/%s/virtualMac/%s/virtualAddress/%s",
		url.PathEscape(serviceName),
		url.PathEscape(mac),
		url.PathEscape(ipAddress),
	)

	task := &DedicatedServerTask{}
	if err := config.OVHClient.Delete(endpoint, task); err != nil {
		return helpers.CheckDeleted(d, err, endpoint)
	}

	if err := waitForDedicatedServerTask(serviceName, task, config.OVHClient); err != nil {
		return fmt.Errorf("Error waiting for virtual MAC %s deletion on %s: %s", mac, serviceName, err)
	}

	d.SetId("")
	return nil
}

func resourceDedicatedServerVirtualMacImportState(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	serviceName, mac, ipAddress, err := dedicatedServerVirtualMacSplitId(d.Id())
	if err != nil {
		return nil, fmt.Errorf("Import Id is not SERVICE_NAME/MAC_ADDRESS/IP_ADDRESS formatted")
	}

	d.Set("service_name", serviceName)
	d.Set("mac_address", mac)
	d.Set("ip_address", ipAddress)

	return []*schema.ResourceData{d}, nil
}

func dedicatedServerVirtualMacSplitId(id string) (serviceName, mac, ipAddress string, err error) {
	parts := strings.SplitN(id, "/", 3)
	if len(parts) != 3 || parts[0] == "" || parts[1] == "" || parts[2] == "" {
		return "", "", "", fmt.Errorf("Id %q is not SERVICE_NAME/MAC_ADDRESS/IP_ADDRESS formatted", id)
	}
	return parts[0], parts[1], parts[2], nil
}

func dedicatedServerVirtualMacForIP(serviceName, ipAddress string, c *ovhwrap.Client) (string, error) {
	var macs []string
	listEndpoint := fmt.Sprintf("/dedicated/server/%s/virtualMac", url.PathEscape(serviceName))
	if err := c.Get(listEndpoint, &macs); err != nil {
		return "", fmt.Errorf("Error calling GET %s:\n\t %q", listEndpoint, err)
	}

	for _, mac := range macs {
		var ips []string
		addrEndpoint := fmt.Sprintf("/dedicated/server/%s/virtualMac/%s/virtualAddress",
			url.PathEscape(serviceName),
			url.PathEscape(mac),
		)
		if err := c.Get(addrEndpoint, &ips); err != nil {
			return "", fmt.Errorf("Error calling GET %s:\n\t %q", addrEndpoint, err)
		}
		for _, ip := range ips {
			if ip == ipAddress {
				return mac, nil
			}
		}
	}

	return "", nil
}
