// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package ovh

import (
	"context"
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	ovhtypes "github.com/ovh/terraform-provider-ovh/v2/ovh/types"
)

func CloudProjectFileStorageShareResourceSchema(ctx context.Context) schema.Schema {
	attrs := map[string]schema.Attribute{
		"availability_zone": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "Availability zone of the share (required in 3AZ regions)",
			MarkdownDescription: "Availability zone of the share (required in 3AZ regions)",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplaceIfConfigured(),
			},
		},
		"created_at": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Share creation date",
			MarkdownDescription: "Share creation date",
		},
		"description": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "Share description",
			MarkdownDescription: "Share description",
		},
		"id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Share ID",
			MarkdownDescription: "Share ID",
		},
		"is_public": schema.BoolAttribute{
			CustomType:          ovhtypes.TfBoolType{},
			Computed:            true,
			Description:         "Whether the share is public",
			MarkdownDescription: "Whether the share is public",
		},
		"name": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "Share name",
			MarkdownDescription: "Share name",
		},
		"network_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "Private network ID",
			MarkdownDescription: "Private network ID",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplaceIfConfigured(),
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"protocol": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Share protocol",
			MarkdownDescription: "Share protocol",
			Validators: []validator.String{
				stringvalidator.OneOf(
					"NFS",
				),
			},
		},
		"region_name": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Region name",
			MarkdownDescription: "Region name",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"service_name": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Required:            true,
			Description:         "Service name",
			MarkdownDescription: "Service name",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"share_network_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "Share network ID",
			MarkdownDescription: "Share network ID",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplaceIfConfigured(),
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"size": schema.Int64Attribute{
			CustomType:          ovhtypes.TfInt64Type{},
			Optional:            true,
			Computed:            true,
			Description:         "Share size in Gigabytes",
			MarkdownDescription: "Share size in Gigabytes",
		},
		"snapshot_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "Snapshot ID used to create the share",
			MarkdownDescription: "Snapshot ID used to create the share",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplaceIfConfigured(),
			},
		},
		"status": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Computed:            true,
			Description:         "Share status",
			MarkdownDescription: "Share status",
			Validators: []validator.String{
				stringvalidator.OneOf(
					"available",
					"awaiting_transfer",
					"backup_creating",
					"backup_restoring",
					"backup_restoring_error",
					"creating",
					"creating_from_snapshot",
					"deleted",
					"deleting",
					"error",
					"error_deleting",
					"extending",
					"extending_error",
					"inactive",
					"manage_error",
					"manage_starting",
					"migrating",
					"migrating_to",
					"replication_change",
					"reverting",
					"reverting_error",
					"shrinking",
					"shrinking_error",
					"shrinking_possible_data_loss_error",
					"unmanage_error",
					"unmanage_starting",
					"unmanaged",
				),
			},
		},
		"subnet_id": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "Subnet ID",
			MarkdownDescription: "Subnet ID",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplaceIfConfigured(),
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"type": schema.StringAttribute{
			CustomType:          ovhtypes.TfStringType{},
			Optional:            true,
			Computed:            true,
			Description:         "Share type",
			MarkdownDescription: "Share type",
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplaceIfConfigured(),
			},
			Validators: []validator.String{
				stringvalidator.OneOf(
					"standard-1az",
				),
			},
		},
	}

	return schema.Schema{
		Description: "Creates a file storage share in a public cloud project.",
		Attributes:  attrs,
	}
}

type CloudProjectFileStorageShareModel struct {
	AvailabilityZone ovhtypes.TfStringValue `tfsdk:"availability_zone" json:"availabilityZone"`
	CreatedAt        ovhtypes.TfStringValue `tfsdk:"created_at" json:"createdAt"`
	Description      ovhtypes.TfStringValue `tfsdk:"description" json:"description"`
	Id               ovhtypes.TfStringValue `tfsdk:"id" json:"id"`
	IsPublic         ovhtypes.TfBoolValue   `tfsdk:"is_public" json:"isPublic"`
	Name             ovhtypes.TfStringValue `tfsdk:"name" json:"name"`
	NetworkId        ovhtypes.TfStringValue `tfsdk:"network_id" json:"networkId"`
	Protocol         ovhtypes.TfStringValue `tfsdk:"protocol" json:"protocol"`
	RegionName       ovhtypes.TfStringValue `tfsdk:"region_name" json:"region"`
	ServiceName      ovhtypes.TfStringValue `tfsdk:"service_name" json:"serviceName"`
	ShareNetworkId   ovhtypes.TfStringValue `tfsdk:"share_network_id" json:"shareNetworkId"`
	Size             ovhtypes.TfInt64Value  `tfsdk:"size" json:"size"`
	SnapshotId       ovhtypes.TfStringValue `tfsdk:"snapshot_id" json:"snapshotId"`
	Status           ovhtypes.TfStringValue `tfsdk:"status" json:"status"`
	SubnetId         ovhtypes.TfStringValue `tfsdk:"subnet_id" json:"subnetId"`
	Type             ovhtypes.TfStringValue `tfsdk:"type" json:"type"`
}

func (v *CloudProjectFileStorageShareModel) MergeWith(other *CloudProjectFileStorageShareModel) {
	if (v.AvailabilityZone.IsUnknown() || v.AvailabilityZone.IsNull()) && !other.AvailabilityZone.IsUnknown() {
		v.AvailabilityZone = other.AvailabilityZone
	}

	if (v.CreatedAt.IsUnknown() || v.CreatedAt.IsNull()) && !other.CreatedAt.IsUnknown() {
		v.CreatedAt = other.CreatedAt
	}

	if (v.Description.IsUnknown() || v.Description.IsNull()) && !other.Description.IsUnknown() {
		v.Description = other.Description
	}

	if (v.Id.IsUnknown() || v.Id.IsNull()) && !other.Id.IsUnknown() {
		v.Id = other.Id
	}

	if (v.IsPublic.IsUnknown() || v.IsPublic.IsNull()) && !other.IsPublic.IsUnknown() {
		v.IsPublic = other.IsPublic
	}

	if (v.Name.IsUnknown() || v.Name.IsNull()) && !other.Name.IsUnknown() {
		v.Name = other.Name
	}

	if (v.NetworkId.IsUnknown() || v.NetworkId.IsNull()) && !other.NetworkId.IsUnknown() {
		v.NetworkId = other.NetworkId
	}

	if (v.Protocol.IsUnknown() || v.Protocol.IsNull()) && !other.Protocol.IsUnknown() {
		v.Protocol = other.Protocol
	}

	if (v.RegionName.IsUnknown() || v.RegionName.IsNull()) && !other.RegionName.IsUnknown() {
		v.RegionName = other.RegionName
	}

	if (v.ServiceName.IsUnknown() || v.ServiceName.IsNull()) && !other.ServiceName.IsUnknown() {
		v.ServiceName = other.ServiceName
	}

	if (v.ShareNetworkId.IsUnknown() || v.ShareNetworkId.IsNull()) && !other.ShareNetworkId.IsUnknown() {
		v.ShareNetworkId = other.ShareNetworkId
	}

	if (v.Size.IsUnknown() || v.Size.IsNull()) && !other.Size.IsUnknown() {
		v.Size = other.Size
	}

	if (v.SnapshotId.IsUnknown() || v.SnapshotId.IsNull()) && !other.SnapshotId.IsUnknown() {
		v.SnapshotId = other.SnapshotId
	}

	if (v.Status.IsUnknown() || v.Status.IsNull()) && !other.Status.IsUnknown() {
		v.Status = other.Status
	}

	if (v.SubnetId.IsUnknown() || v.SubnetId.IsNull()) && !other.SubnetId.IsUnknown() {
		v.SubnetId = other.SubnetId
	}

	if (v.Type.IsUnknown() || v.Type.IsNull()) && !other.Type.IsUnknown() {
		v.Type = other.Type
	}
}

func (v CloudProjectFileStorageShareModel) ToCreate() *CloudProjectFileStorageShareCreateModel {
	res := &CloudProjectFileStorageShareCreateModel{}

	if !v.AvailabilityZone.IsUnknown() {
		res.AvailabilityZone = v.AvailabilityZone
	}

	if !v.Description.IsUnknown() {
		res.Description = v.Description
	}

	if !v.Name.IsUnknown() {
		res.Name = v.Name
	}

	if !v.NetworkId.IsUnknown() {
		res.NetworkId = v.NetworkId
	}

	if !v.ShareNetworkId.IsUnknown() {
		res.ShareNetworkId = v.ShareNetworkId
	}

	if !v.Size.IsUnknown() {
		res.Size = v.Size
	}

	if !v.SnapshotId.IsUnknown() {
		res.SnapshotId = v.SnapshotId
	}

	if !v.SubnetId.IsUnknown() {
		res.SubnetId = v.SubnetId
	}

	if !v.Type.IsUnknown() {
		res.Type = v.Type
	}

	return res
}

func (v CloudProjectFileStorageShareModel) ToUpdate() *CloudProjectFileStorageShareUpdateModel {
	res := &CloudProjectFileStorageShareUpdateModel{}

	if !v.Description.IsUnknown() {
		res.Description = v.Description
	}

	if !v.Name.IsUnknown() {
		res.Name = v.Name
	}

	if !v.Size.IsUnknown() {
		res.NewSize = v.Size
	}

	return res
}

type CloudProjectFileStorageShareCreateModel struct {
	AvailabilityZone ovhtypes.TfStringValue `json:"availabilityZone"`
	Description      ovhtypes.TfStringValue `json:"description"`
	Name             ovhtypes.TfStringValue `json:"name"`
	NetworkId        ovhtypes.TfStringValue `json:"networkId"`
	ShareNetworkId   ovhtypes.TfStringValue `json:"shareNetworkId"`
	Size             ovhtypes.TfInt64Value  `json:"size"`
	SnapshotId       ovhtypes.TfStringValue `json:"snapshotId"`
	SubnetId         ovhtypes.TfStringValue `json:"subnetId"`
	Type             ovhtypes.TfStringValue `json:"type"`
}

func (v *CloudProjectFileStorageShareCreateModel) MarshalJSON() ([]byte, error) {
	toMarshal := map[string]any{}

	if !v.Type.IsNull() && !v.Type.IsUnknown() {
		toMarshal["type"] = v.Type
	}
	if !v.AvailabilityZone.IsNull() && !v.AvailabilityZone.IsUnknown() {
		toMarshal["availabilityZone"] = v.AvailabilityZone
	}
	if !v.Description.IsNull() && !v.Description.IsUnknown() {
		toMarshal["description"] = v.Description
	}
	if !v.Name.IsNull() && !v.Name.IsUnknown() {
		toMarshal["name"] = v.Name
	}
	if !v.NetworkId.IsNull() && !v.NetworkId.IsUnknown() {
		toMarshal["networkId"] = v.NetworkId
	}
	if !v.ShareNetworkId.IsNull() && !v.ShareNetworkId.IsUnknown() {
		toMarshal["shareNetworkId"] = v.ShareNetworkId
	}
	if !v.Size.IsNull() && !v.Size.IsUnknown() {
		toMarshal["size"] = v.Size
	}
	if !v.SnapshotId.IsNull() && !v.SnapshotId.IsUnknown() {
		toMarshal["snapshotId"] = v.SnapshotId
	}
	if !v.SubnetId.IsNull() && !v.SubnetId.IsUnknown() {
		toMarshal["subnetId"] = v.SubnetId
	}

	return json.Marshal(toMarshal)
}

type CloudProjectFileStorageShareUpdateModel struct {
	Description ovhtypes.TfStringValue `json:"description"`
	Name        ovhtypes.TfStringValue `json:"name"`
	NewSize     ovhtypes.TfInt64Value  `json:"newSize"`
}

func (v *CloudProjectFileStorageShareUpdateModel) MarshalJSON() ([]byte, error) {
	toMarshal := map[string]any{}

	if !v.Description.IsNull() && !v.Description.IsUnknown() {
		toMarshal["description"] = v.Description
	}
	if !v.Name.IsNull() && !v.Name.IsUnknown() {
		toMarshal["name"] = v.Name
	}
	if !v.NewSize.IsNull() && !v.NewSize.IsUnknown() {
		toMarshal["newSize"] = v.NewSize
	}

	return json.Marshal(toMarshal)
}
